### ISSUE TITLE
The SmartThings Smart App cannot be removed from SmartThings Classic

### ISSUE THREAD

**Issue by jdestefanis** [andrewsayre/hass-smartthings-remove#3]
Background History

I were using mosquitto and SmartThings Bridge plugin so far without any issue. Then, I have updated my Hass.io and wanted to test this plugin. I have configured it with no much troubles. It wasn't easy to understand the new nomenclature and how to show the sensors, but finally it worked.
After a few days, 2 of my sensors stopped reporting data to Hass.IO but they continue reporting correctly to the SmartThings Classic app. When that issue started I have tried everything to fix it and nothing worked. Then I have decided to remove the integration, then I removed the token I have used to connect HA to my Smart App on SmartThings Classic.
I created a new token, I started the integration process again form HA, but when I submitted the token it says: "Please install the Home Assistant SmartApp in at least one location and click submit" - Of course I have the SmartApp installed but I cannot uninstall it from the SmartThings Classic App anymore because it popups with an error when trying to get access to it.

Finally, I have tried to create a new token and when I do that, I can enter into the Home Assistant SmartApp but, it is trying to Authorize the SmartThings App instead the SmartThings Classic app (I don't know if this is or not related to) By then, when you try to submit with the new token, HA says: "Please ensure you have installed and authorized the Home Assistant SmartApp and try again." - It means that the Classic app is not being authorized.

![IMG_0512](https://user-images.githubusercontent.com/8029197/54569459-ba024880-49b9-11e9-98fc-899ff2b16b39.PNG)

![Home_Assistant](https://user-images.githubusercontent.com/8029197/54569466-c1295680-49b9-11e9-8e6f-288758deda2c.jpg)

![Image-1](https://user-images.githubusercontent.com/8029197/54569559-11a0b400-49ba-11e9-8d1e-5cd03ef3a588.jpg)

![Image-1__1__jpg](https://user-images.githubusercontent.com/8029197/54569621-5298c880-49ba-11e9-9f3c-7c69206e972d.jpg)

**Comment by andrewsayre** [comment]
It looks to me you have issues with ST sending messages to HASS, a problem with your firewall, router, or reverse proxy.  It's not clear from your post... did you run the removal utility to clean up the previous apps?  What was the output when you ran it?

**Comment by cvccole** [comment]
I am having a similar problem. I had 4 instances of the smart app installed. I ran the program and it removed one of them.

![PIP](https://user-images.githubusercontent.com/30178217/56380530-636a7300-61e0-11e9-93f8-fbd9ce29f046.JPG)

**Comment by andrewsayre** [comment]
@cvccole Did you notice you didn't replace `PERSONAL_ACCESS_TOKEN` with your token?

**Comment by andrewsayre** [comment]
I'm closing this issue as OP has not responded in a month.

**Comment by cvccole** [comment]
Ah that’s why it only removed the 1 that I had working last. I only had a copy of the latest one. Saw your post by chance & thought I would give it a try to remove the old ones.

**Comment by andrewsayre** [comment]
It wouldn't have removed anything without your token.  It can't do anything without that.  :) Probably just lag in the app or needing to refresh.  Please open a new issue if you're having trouble.  Locking thread.
