### ISSUE TITLE
Unable to run the script

### ISSUE THREAD

**Issue by nelsontyc** [andrewsayre/hass-smartthings-remove#5]
Hi, I am writing as a newbie with running this code. I am getting syntax errors, so will need your help to see if i am even doing it correctly. Thank you so much! (I changed the token number to a dummy one in this screenshot, but the error is the same even if I used the real one)

![image](https://user-images.githubusercontent.com/51257403/58745399-0a4e5a00-8483-11e9-8e3d-091573dd93de.png)

**Comment by Helbo15** [comment]
I got the same problem I'm guessing it is because I'm not using it correctly ?

**Comment by Neu-Bob** [comment]
does this script have to be run from the hassos device?

Can it be run from a mac or windows pc?
