### ISSUE TITLE
newbie help

### ISSUE THREAD

**Issue by JamieP83** [andrewsayre/hass-smartthings-remove#6]
Hey,
im not sure where to even start?
where do i run this PIP command from sorry?

im running Hassio on a RPI4 and need to clean up 3 HA "apps" which all show up  in ST

**Comment by sawo69** [comment]
If you are running hassio you should use commando "python3 -m pip ......" in a shell

**Comment by ThatGuySM** [comment]
Could someone PLEASE give a step by step in how to run this via HASSIO?

**Comment by Neu-Bob** [comment]
I'm running hassos... i install python but can not execute pip3 or pip commands... suggestions?

**Comment by srvoets** [comment]
same

**Comment by ILAsoft** [comment]
Hassos - able to run pip and python3 via SSH, but still getting error:
```
Building wheels for collected packages: multidict
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp_j8i0hzl
       cwd: /tmp/pip-install-0kchg_oe/multidict_cc7b9a97f5c24868a0a3b58c16a69734
.........................
  creating build/temp.linux-aarch64-3.9/multidict
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c multidict/_multidict.c -o build/temp.linux-aarch64-3.9/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly
```

**Comment by aklausen** [comment]
> Hassos - able to run pip and python3 via SSH, but still getting error:
> 
> ```
> Building wheels for collected packages: multidict
>   Building wheel for multidict (PEP 517) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp_j8i0hzl
>        cwd: /tmp/pip-install-0kchg_oe/multidict_cc7b9a97f5c24868a0a3b58c16a69734
> .........................
>   creating build/temp.linux-aarch64-3.9/multidict
>   gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c multidict/_multidict.c -o build/temp.linux-aarch64-3.9/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
>   error: command 'gcc' failed: No such file or directory
>   ----------------------------------------
>   ERROR: Failed building wheel for multidict
> Failed to build multidict
> ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly
> ```

Hello did ever get this to work i have the same problem
